### ISSUE TITLE
 Unsupported URL Type "workspace:": workspace:*

### ISSUE THREAD

**Issue by mikekuzak** [jorge-menjivar/unsaged#104]
In order to build the project I'm adding ```npm i``` into the Dockerfile. Otherwise this doesn't work on a host without npm. 
This approach worked yesterday. 

```
# ---- Dependencies ----
FROM base AS dependencies
RUN npm i
RUN npm ci
```

Today looks like it's breaking when I get the latest version form main. 
```
npm notice
npm notice New major version of npm available! 9.6.3 -> 10.2.4
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>
npm notice Run `npm install -g npm@10.2.4` to update!
npm notice
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-11-23T11_47_26_971Z-debug-0.log
```
I can see commits have been made to the package.json file.

**Comment by mikekuzak** [comment]
Think the [Dockerfile ](https://github.com/jorge-menjivar/unsaged/blob/dev/apps/unsaged/Dockerfile) needs to be rewritten to support the change of pnpm

**Comment by sebiweise** [comment]
Yes thats correct, I think the docker file needs to be updates to pnpm and also adapted to the new turbo repo structure.

**Comment by Bortus-AI** [comment]
> In order to build the project I'm adding `npm i` into the Dockerfile. Otherwise this doesn't work on a host without npm. This approach worked yesterday.
> 
> ```
> # ---- Dependencies ----
> FROM base AS dependencies
> RUN npm i
> RUN npm ci
> ```
> 
> Today looks like it's breaking when I get the latest version form main.
> 
> ```
> npm notice
> npm notice New major version of npm available! 9.6.3 -> 10.2.4
> npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>
> npm notice Run `npm install -g npm@10.2.4` to update!
> npm notice
> npm ERR! code EUNSUPPORTEDPROTOCOL
> npm ERR! Unsupported URL Type "workspace:": workspace:*
> 
> npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-11-23T11_47_26_971Z-debug-0.log
> ```
> 
> I can see commits have been made to the package.json file.

Try this and let me know if it works for you. Works in my Coolify docker app


`# ---- Base Node ----
FROM node:19-alpine AS base
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package files
COPY package*.json pnpm-lock.yaml ./
COPY .env.local .env.local

# ---- Dependencies ----
FROM base AS dependencies
# Install dependencies with pnpm
RUN pnpm install --frozen-lockfile

# ---- Build ----
FROM dependencies AS build
COPY . .
# Build the application
RUN pnpm run build

# ---- Production ----
FROM node:19-alpine AS production
RUN apk update && apk add --no-cache curl
WORKDIR /app

# Copy necessary files
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/package*.json ./
COPY --from=build /app/next.config.js ./next.config.js
COPY --from=build /app/next-i18next.config.js ./next-i18next.config.js

# Expose the port the app will run on
EXPOSE 3000

# Start the application
CMD ["pnpm", "start"]
`

**Comment by Bortus-AI** [comment]
> No luck.
> 
> * clone from master
> * cd unsaged/apps/unsaged
> 
> Will complain about missing pnpm-lock.yaml So I copied it from root:
> 
> ```
> $ cp ../../pnpm-lock.yaml .
> $ cp ../../package.json .
> ```
> 
> ```
> Sending build context to Docker daemon  2.192MB
> Step 1/21 : FROM node:19-alpine AS base
>  ---> e2a8cc97f817
> Step 2/21 : WORKDIR /app
>  ---> Using cache
>  ---> c16f1b42f5ab
> Step 3/21 : RUN npm install -g pnpm
>  ---> Using cache
>  ---> b11eff3dab53
> Step 4/21 : COPY package*.json pnpm-lock.yaml ./
>  ---> Using cache
>  ---> 4566546a5a3c
> Step 5/21 : COPY .env.local .env.local
>  ---> Using cache
>  ---> cebbd926d3de
> Step 6/21 : FROM base AS dependencies
>  ---> cebbd926d3de
> Step 7/21 : RUN pnpm install --frozen-lockfile
>  ---> Using cache
>  ---> 147977990791
> Step 8/21 : FROM dependencies AS build
>  ---> 147977990791
> Step 9/21 : COPY . .
>  ---> 95fcf422683c
> Step 10/21 : RUN pnpm run build
>  ---> Running in f060c6a35729
>  WARN  The "workspaces" field in package.json is not supported by pnpm. Create a "pnpm-workspace.yaml" file instead.
> 
> > monorepo@ build /app
> > turbo run build
> 
> • Running build
> • Remote caching disabled
> root task build (turbo run build) looks like it invokes turbo and might cause a loop
> No tasks were executed as part of this run.
> 
> 
>  Tasks:    0 successful, 0 total
> Cached:    0 cached, 0 total
>   Time:    1.064s
> 
>  ERROR  run failed: command  exited (1)
>  ELIFECYCLE  Command failed with exit code 1.
> The command '/bin/sh -c pnpm run build' returned a non-zero code: 1
> ```

Okay let me work on a proper docket file for standard use. My environment is a bit different so I'll switch to my other server.

What os you running?

**Comment by mikekuzak** [comment]
one with npm installed :)  .. Oracle Linux or Linux Flatcar

**Comment by Bortus-AI** [comment]
Ooooo lol Might be a bit beyond my knowledge but I'll play with it once I wrap up work

**Comment by Bortus-AI** [comment]
I also have a GitHub workflow to make this image on their free servers and post it in dockerhub. I need to tweak it due to the recent changes but that's another option

**Comment by mikekuzak** [comment]
that even better!

**Comment by Bortus-AI** [comment]
If you want a copy of my dockerfile I can share it
