### ISSUE TITLE
[Docs] Bad link for generation script on Getting Started page

### ISSUE THREAD

**Issue by aordano** [jorge-menjivar/unsaged#113]
The Supabase generation script on the [getting started page](https://unsaged.com/docs/getting-started/installation) is [currently this](https://github.com/jorge-menjivar/unSAGED/apps/unsaged/db/GenerationScript.sql) but it should be [this one](https://raw.githubusercontent.com/jorge-menjivar/unsaged/dev/apps/unsaged/db/GenerationScript.sql).

Apparently there was a name change or something and the original link is no longer up to date.

**Comment by Bortus-AI** [comment]
Thanks for the report. I made the change and waiting for it to get merged.

**Comment by jorge-menjivar** [comment]
Fixed by #115 and #116
