### ISSUE TITLE
Blank Page Issue with Latest Build in Docker Environment

### ISSUE THREAD

**Issue by mbronze** [jorge-menjivar/unsaged#151]
Hi Jorge,

I encountered an issue with the latest build: it compiles and runs in Docker, but accessing the server only loads the database and conversations partially before showing a blank page. No login screen appears. The logs indicate all models as "Not implemented."

Could this be a configuration miss on my end or a bug in the code?

Thanks for your help,

Mario

**Comment by Bortus-AI** [comment]
@mbronze I am not able to reproduce this. Can you share the console logs from your page via chrome developer page. Once on the unsaged page right click and click inspect and then click the console tab

**Comment by mbronze** [comment]
sure, here is;

[chatbot.digitaldevices.ca-1702948766019.log](https://github.com/jorge-menjivar/unsaged/files/13709978/chatbot.digitaldevices.ca-1702948766019.log)

**Comment by Bortus-AI** [comment]
Invalid API key', hint: 'Double check your Supabase `anon` or `service_role` API key.'}

Did you have the supabase variables set in the .env.local prior to building the docker image? This usually happens when the .env.local is not present in the apps/unsaged folder prior to building

**Comment by mbronze** [comment]
Found the problem not on the .env.local but on Portainer Stack the env variables for supabase  not copied properly.
I guess it override the variables set on the .env.local of the build.
To avoid issues we should just place the env variables in one place or .env.local on root or portainer stack (Docker Compose).
Working good now.
Thank you Very Much
