### ISSUE TITLE
[BUG] npm dependency issue

### ISSUE THREAD

**Issue by pureair** [jorge-menjivar/unsaged#158]
**npm dependency issue on vitest**

**To Reproduce**
1. Follow the Installation Guide https://unsaged.com/docs/getting-started/installation
2. When running "npm i" in ~/unSAGED/apps/unsaged, error reported as follow

```
# npm resolution error report 

While resolving: unsaged@0.0.1
Found: vitest@1.0.4
node_modules/vitest
  dev vitest@"^1.0.4" from unsaged@0.0.1
  apps/unsaged
    unsaged@0.0.1
    node_modules/unsaged
      workspace apps/unsaged from the root project
  peer vitest@"^1.0.0" from @vitest/browser@1.0.4
  node_modules/@vitest/browser
    peerOptional @vitest/browser@"^1.0.0" from vitest@1.0.4
  peer vitest@"^1.0.0" from @vitest/ui@1.0.4
  node_modules/@vitest/ui
    peerOptional @vitest/ui@"^1.0.0" from vitest@1.0.4

Could not resolve dependency:
peer vitest@">=0.30.0 <1" from @vitest/coverage-c8@0.33.0
node_modules/@vitest/coverage-c8
  dev @vitest/coverage-c8@"^0.33.0" from unsaged@0.0.1
  apps/unsaged
    unsaged@0.0.1
    node_modules/unsaged
      workspace apps/unsaged from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Debian 12

**Additional context**
Running "docker build -t unsaged -f apps/unsaged/Dockerfile . --rm" in ~/unSAGED hung as well.

**Comment by sebiweise** [comment]
You will have to use pnpm instead of npm then it should work fine, I will update the docs to reflect this step correctly.

**Comment by Bortus-AI** [comment]
@pureair I pushed an update. Until its merged try the updated instructions via this commit

https://github.com/Bortus-AI/unsaged/blob/ac1694eae69c63213501b1cb880c9d317a47a7d2/apps/docs/docs/getting-started/installation.md
