### ISSUE TITLE
Error when DEFAULT_MODEL not defined in .env.local and running locally

### ISSUE THREAD

**Issue by johnbrownlow** [jorge-menjivar/unSAGED#16]
Title says it all. The readme says it defaults to GPT-3.5-Turbo but in my case it threw an error. When I defined it explicitly it worked fine.

Error: Error serializing `.defaultModelId` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.

**Comment by jorge-menjivar** [comment]
Should be fixed now by #17
