### ISSUE TITLE
System prompts don't populate system prompt menu

### ISSUE THREAD

**Issue by johnbrownlow** [jorge-menjivar/unSAGED#25]
If I create a new system prompt, it shows in the list of system prompts but doesn't populate the menu on the right, which continues to only offer the default prompts.

**Comment by jorge-menjivar** [comment]
@johnbrownlow Are you making sure to select the models for which to make the sys prompts available for? For example, below I made it available only to the anthropic models.

![Screenshot from 2023-09-01 13-55-05](https://github.com/jorge-menjivar/unSAGED/assets/16660534/02e8f74e-dab0-4c4d-86cc-cc83e191753b)
![Screenshot from 2023-09-01 13-56-11](https://github.com/jorge-menjivar/unSAGED/assets/16660534/f4222485-5026-4375-a3d0-d4ad7563d334)
![Screenshot from 2023-09-01 13-56-21](https://github.com/jorge-menjivar/unSAGED/assets/16660534/862340fb-1cd4-43d0-97ca-7163330bbf69)

**Comment by jorge-menjivar** [comment]
@johnbrownlow did you have any updates on this?

**Comment by jorge-menjivar** [comment]
I will close this for now. I will re-open if the issue if it appears again.
