### ISSUE TITLE
Black login screen

### ISSUE THREAD

**Issue by navyfighter12** [jorge-menjivar/unSAGED#36]
I added everything it my .env.local and started the script but I end up with a black screen with the url and can't login
http://localhost:3000/api/auth/signin?callbackUrl=%2F

![image](https://github.com/jorge-menjivar/unSAGED/assets/100248124/59159a27-88f8-4c90-904f-22368c5b94e5)

**Comment by brinrbc** [comment]
> navyfighter12

hello colleague) and how did you solve this problem? I can't figure out what to do

**Comment by ramicaza** [comment]
+1
