### ISSUE TITLE
How to activate the Auth with Email + password with supabase

### ISSUE THREAD

**Issue by Bamorem** [jorge-menjivar/unSAGED#4]
Can you help me to add the email + password as a auth provider ?
from what i was able to do is to only do it with SSO like google + github
but how can i do to add for email and password using supabase auth ?

Thanks for your help

**Comment by jorge-menjivar** [comment]
Let's move this to the discussion section, I think it would be more appropriate. I would love to help, let's continue the talk there.

**Comment by jorge-menjivar** [comment]
I will leave this open, because it is technically a feature request as there is no support for this right now. However, we should still discuss about adding this feature in the discussion section.

**Comment by jorge-menjivar** [comment]
#5

**Comment by Bamorem** [comment]
Great you're the best

**Comment by jorge-menjivar** [comment]
#34 adds support for this
