### ISSUE TITLE
Ollama Code code block syntax issue

### ISSUE THREAD

**Issue by Bortus-AI** [jorge-menjivar/unsaged#42]
unSAGED does not seem to identify the code blocks correctly for vba code.

It looks to use \begin{code} and \end{code} which is not recognized maybe? [](url)

See attached screenshot of the issue

![image](https://github.com/jorge-menjivar/unSAGED/assets/100248124/ea690dc6-286a-4c9f-9c3b-749a3cdbc263)

**Comment by navyfighter12** [comment]
I will test if it does it with other code like python or just VBA

**Comment by jorge-menjivar** [comment]
This looks like it might be related to the system prompt itself. Try making a custom system prompt for the model you are using and tell it to surround code "```vbnet" instead  of `\begin{code}` as that would not be readable in markdown syntax.

**Comment by navyfighter12** [comment]
> This looks like it might be related to the system prompt itself. Try making a custom system prompt for the model you are using and tell it to surround code "```vbnet" instead of `\begin{code}` as that would not be readable in markdown syntax.

Thanks I will give that a try
