### ISSUE TITLE
Infinite redirect loop after google login

### ISSUE THREAD

**Issue by diegosc78** [jorge-menjivar/unsaged#47]
I've followed the 7 steps in readme, mapping a /etc/host dns name for the application and using it in .env.local

- Application loads OK
- Google authentication finishes OK (no errors after login, row in next_auth schema tables, browser redirects)
- Browser redirects to http://thedomainiveconfigured:3000/es
- Infinite redirect loop

Any clue?

**Comment by jorge-menjivar** [comment]
Hmm, it looks like an issue with language configuration. It seems like it is trying to go to the Spanish version of the site, which isn't there. I will need to look into it a bit more.

**Comment by diegosc78** [comment]
Thank you very much. I changed browser language preferences to english and it worked. I'll dig a bit to guess how to extend or configure your code for adding new languages or jumping to a default language if it doesn't find browser one. Thanks again

**Comment by jorge-menjivar** [comment]
The project was previously using https://github.com/i18next/next-i18next to support multiple languages. However they do not support the new NextJS app dir so it had to be dropped. 

Going forward it would probably be best to stick with the default NextJS implementation documented here https://nextjs.org/docs/app/building-your-application/routing/internationalization or a tool built on top of that
