### ISSUE TITLE
Block login screen

### ISSUE THREAD

**Issue by brinrbc** [jorge-menjivar/unSAGED#48]
I added everything it my .env.local and started the script but I end up with a black screen with the url and can't login
http://localhost:3000/api/auth/signin?callbackUrl=%2F
![277186724-59159a27-88f8-4c90-904f-22368c5b94e5](https://github.com/jorge-menjivar/unSAGED/assets/112558726/96c8ea27-229c-4d7e-b178-129dd19ea1bc)

**Comment by jorge-menjivar** [comment]
Make sure the env variables are not misspelled. This usually happens when the app cannot find any configurations for auth providers. 

Also enable debug mode with `NEXT_PUBLIC_DEBUG_MODE=true` in the env file to print out all the variables the app is able to see.
