### ISSUE TITLE
[BUG] Rate limit reached for gpt-4 in organization

### ISSUE THREAD

**Issue by sebiweise** [jorge-menjivar/unSAGED#53]
**Describe the bug**
For any reason I´m getting the following error when using GPT-4. After 4-5 Messages I´m getting a rate limit error on the server. Any idea why this is coming?

**Additional context**
{
  message: 'Rate limit reached for gpt-4 in organization ***** on tokens per min. Limit: 10000 / min. Please try again in 6ms. Visit https://platform.openai.com/account/rate-limits to learn more.',
  type: 'tokens',
  param: null,
  code: 'rate_limit_exceeded'
}

**Comment by jorge-menjivar** [comment]
Are you continuing to experience this? I have experienced this in the past, but it was an issue with the OpenAI API. They announced GPT-4-Turbo yesterday, so I suspect it could have been an issue with their servers from the extra load.

**Comment by sebiweise** [comment]
Yes I just tested the new gpt-4-turbo-preview and the error is gone.

**Comment by jorge-menjivar** [comment]
Sounds good. Don't hesitate to reach out again if the issue comes back.
