### ISSUE TITLE
[BUG] Section personalization not found

### ISSUE THREAD

**Issue by sebiweise** [jorge-menjivar/unSAGED#55]
**Describe the bug**
When I login I got stuck to the loading screen "Loading Conversations..."
Console is showing the error "Section personalization not found"

**Screenshots**
![image](https://github.com/jorge-menjivar/unSAGED/assets/22999200/89111de2-e113-4041-ad3d-0e18e28d7164)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Browser version latest

**Comment by sebiweise** [comment]
Local storage debug is just showing the nextauth.message: "{"event":"session","data":{"trigger":"getSession"},"timestamp":1699362676}"

**Comment by jorge-menjivar** [comment]
That error should actually just be a warning and not affect the app. It is basically checking to see if you have set a preference for light or dark theme and should default to dark if nothing is set.
Try setting `NEXT_PUBLIC_DEBUG_MODE=true` in the .env file and see the console to check if all the env variables are being read correctly, client and server side. Also, check the browser network logs, you should see an error there if it is not connecting to supabase.

**Comment by sebiweise** [comment]
Getting the /api/models result into
[POST] /api/models reason=EDGE_FUNCTION_INVOCATION_TIMEOUT, status=504, user_error=true

**Comment by jorge-menjivar** [comment]
We need to implement a timeout on our side to prevent the whole model fetching from crashing. I will make a note of that. In the meantime, I know you mentioned in another issue that you are using ollama. Could it be that it gets stuck trying to connect to the ollama server?

**Comment by sebiweise** [comment]
Yes I just checked that, so my Ollama server is not reachable, the fetch call is taking to long and therefor the api call to `/api/models` results in a timeout.

**Comment by sebiweise** [comment]
Yes so removing the ollama host variable "resolved" the problem. I think getting the ollama models isn´t working 100%

**Comment by jorge-menjivar** [comment]
Does it work okay if you deploy locally?

**Comment by sebiweise** [comment]
I will test to run it on my local pc and connect to my external ollama server, maybe Vercel requires https to connect to external resources or maybe the default port of ollama 11434 isn´t allowed on Vercel infra.

**Comment by jorge-menjivar** [comment]
Keep me updated. Thanks!

**Comment by sebiweise** [comment]
Yes so Vercel isn´t working with the port 11434 for me, when I reverse proxy my ollama api to https://ollama.mydomain.com it is working fine on Vercel.
