### ISSUE TITLE
Persist temperature setting between conversations

### ISSUE THREAD

**Issue by Boscop** [jorge-menjivar/unSAGED#60]
It seems whenever I start a new conversation, the temperature is reset to 0.7, and there is no way to save a custom default or persist the current value between conversations?

**Comment by jorge-menjivar** [comment]
We forgot to document it, but you can set NEXT_PUBLIC_DEFAULT_TEMPERATURE to another value to change the default temperature.  For the record, you can also see pretty much all variables you can change here, in case that we ever miss something in the documentation: https://github.com/jorge-menjivar/unSAGED/blob/main/utils/app/const.ts

**Comment by Boscop** [comment]
I meant on https://unsaged.com :)
But it seems not to happen anymore. 
But sometimes it doesn't remember my selected model between sessions and resets to gpt-3.5-turbo even though I had selected gpt-4-1106-preview in the previous session.

**Comment by jorge-menjivar** [comment]
I will be doing some improvements in the upcoming days to add other model parameters. I will look at this issue then.
