### ISSUE TITLE
google auth doesn't work

### ISSUE THREAD

**Issue by Bamorem** [jorge-menjivar/unSAGED#7]
Hi, I'm trying to setup the google auth SSO using supabase:

but when i click on the login button i got redirect to this url:
https://xxxxxxxxx.supabase.co/api/auth/signin/google

with an error message saying : {"message":"No API key found in request","hint":"No `apikey` request header or url param was found."}

my env file look like this:

OPENAI_API_KEY=xxxx
NEXT_PUBLIC_AUTH_ENABLED=true

NEXT_PUBLIC_SUPABASE_URL=https://xxxxxxx.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=xxxxxxxx

SUPABASE_SERVICE_ROLE_KEY=xxxxxxx
SUPABASE_JWT_SECRET=xxxxxxxxxx
NEXTAUTH_SECRET=xxxxxxxx
NEXTAUTH_URL=https://xxxxxx.supabase.co

GOOGLE_CLIENT_ID=xxxxxxx-xxxxxxxx.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=xxxxxxxx
GOOGLE_API_KEY=xxxxxxxx

**Comment by jorge-menjivar** [comment]
NEXTAUTH_URL should point to the location where your app is being hosted. In development this would be localhost:3000. In production this will be your domain.
