### ISSUE TITLE
Development branch

### ISSUE THREAD

**Issue by sebiweise** [jorge-menjivar/unSAGED#72]
I think it would be great to create a develop branch and maybe stick to something like Gitflow so each update can be created in a feature branch, will be merged and tested in develop and then is merged working in main.

**Comment by jorge-menjivar** [comment]
I like this idea. We need to make our flow a bit more professional. Also join our discord if you haven’t, we discuss smaller stuff there

**Comment by sebiweise** [comment]
dev Branch was created.
