### ISSUE TITLE
[BUG] Language feature not working

### ISSUE THREAD

**Issue by sebiweise** [jorge-menjivar/unsaged#73]
**Describe the bug**
I´m getting a 404 NOT_FOUND when I´m getting auto redirected to /de. When I type /en manually everything is working fine.

**To Reproduce**
1. Go to 'https://app.unsaged.com/de'

**Screenshots**
![image](https://github.com/jorge-menjivar/unSAGED/assets/22999200/1e42666d-e80c-4560-9d65-f5cab8660d72)

**Comment by jorge-menjivar** [comment]
This looks to be related to #47. We need to fix support for other languages.
