### ISSUE TITLE
NEW OPEN AI MODELS IE -turbo-16k-0613	16,384 tokens

### ISSUE THREAD

**Issue by GEMTechnologies** [jorge-menjivar/unSAGED#8]
Kindly can u update this including gpt-3.5-turbo-16k-0613

**Comment by jorge-menjivar** [comment]
This has been implemented in the last update that I pushed just now

**Comment by shaggy2626** [comment]
@jorge-menjivar Where can I set the Max token and how do I change the default system prompt?
