### ISSUE TITLE
[Help Needed] Fix support for other languages

### ISSUE THREAD

**Issue by daniel-farina** [jorge-menjivar/unsaged#89]
More information on: https://github.com/jorge-menjivar/unSAGED/issues/47 and https://github.com/jorge-menjivar/unSAGED/issues/73

Result: 
Multiple language redirect should work.

**Comment by diegosc78** [comment]
Maybe this could help? https://github.com/vercel/next.js/discussions/18419 

I'm absolutely newbie with next.js... but interested in this fix... so if I would like to help
