### ISSUE TITLE
[Help Needed] - Is a on-prem supabase install supported ? 

### ISSUE THREAD

**Issue by mikekuzak** [jorge-menjivar/unSAGED#90]
Expose the next_auth schema
Expose the next_auth schema in the [API settings](https://app.supabase.com/project/_/settings/api) by adding next_auth to the "Exposed schemas" list.

More information [here](https://authjs.dev/reference/adapter/supabase#expose-the-nextauth-schema-in-supabase).

Then copy the output and save it for the next step.

API settings don't exists in the UI in a self hosted instance.

**Comment by sebiweise** [comment]
I just created a PR #83 where you can find the settings for your local Supabase instance. In the config.toml you can define the API schemas to expose:
https://github.com/jorge-menjivar/unSAGED/pull/83/files#diff-56c3d03bfaddf3efa07a4efe3dd767c0ecc36441ffe865ee5865794b066ee2faR10

**Comment by mikekuzak** [comment]
@sebiweise Where is the [supabase/config.toml] file in the docker setup ? Which container does host that ? Any docker env. variables to set this up ?

**Comment by sebiweise** [comment]
The config.toml I´ve linked in the privous comment is just for the supabse-cli to get your development env up and running.

**Comment by mikekuzak** [comment]
Hmm I'm using the supabase docker self-hosted setup. 
https://supabase.com/docs/guides/self-hosting/docker
