### ISSUE TITLE
[Question] - 401 on access to conversation table in Supabase

### ISSUE THREAD

**Issue by mikekuzak** [jorge-menjivar/unsaged#98]
Hi,

I'm using a docker self-hosted install of supabase. have done the setup, created a user with email address in supabase and connected unsaged with all the Keys to the supabase instance. 

I can login via email authentication, will get redirected back to unsaged and I'm getting a black screen. 
It looks like I'm getting a 401 on trying to get to the conversation resource. 

Do I need to assign the supabase user to these tables, or maybe there needs to be an project API key defined in the unsaged config ? 

![image](https://github.com/jorge-menjivar/unSAGED/assets/18675587/89394fe2-9b4e-46b6-81cc-5dbea6871945)

I used the generation script 
https://github.com/jorge-menjivar/unSAGED/blob/dev/packages/unsaged/db/GenerationScript.sql
via the SQL Editor.

Thanks for any advise.

**Comment by daniel-farina** [comment]
Do you want to try this PR https://github.com/jorge-menjivar/unSAGED/pull/97 ?  would love some feedback. 

It replaces next-auth with supabase-auth and makes the setup a lot easier, no jw tokens needed and the magic link should work out of the box.

**Comment by daniel-farina** [comment]
also make sure you .env has the right parameters for supabase on the error your mentioned earlier.

**Comment by mikekuzak** [comment]
> Do you want to try this PR #97 ? would love some feedback.
> 
> It replaces next-auth with supabase-auth and makes the setup a lot easier, no jw tokens needed and the magic link should work out of the box.

Yeah sure .. but I need a working unsaged container first. The current Dockerfile is not working. 

              Yes thats correct, I think the docker file needs to be updates to pnpm and also adapted to the new turbo repo structure.

_Originally posted by @sebiweise in https://github.com/jorge-menjivar/unsaged/issues/104#issuecomment-1824574726_

**Comment by sebiweise** [comment]
> > Do you want to try this PR #97 ? would love some feedback.
> 
> > 
> 
> > It replaces next-auth with supabase-auth and makes the setup a lot easier, no jw tokens needed and the magic link should work out of the box.
> 
> 
> 
> Yeah sure .. but I need a working unsaged container first. The current Dockerfile is not working. 
> 
> 
> 
>               Yes thats correct, I think the docker file needs to be updates to pnpm and also adapted to the new turbo repo structure.
> 
> 
> 
> _Originally posted by @sebiweise in https://github.com/jorge-menjivar/unsaged/issues/104#issuecomment-1824574726_

I will have a look at the dockerfile tomorrow and I will try to fix it as soon as possible.

**Comment by Bortus-AI** [comment]
Resolved with new docker file per #120
